= Slip boundary conditions
Christophe Prud'homme
v0, 2017/04/30
:page-permalink: /slip
:page-root: /
:page-layout: default
:docinfo: shared
include::includes/header.adoc[]
stem: latexmath

We consider the Stokes equation with parts of the boundary where we impose the normal component of the velocity.
Doing this means that we also have to control the tangential components of the stress to complete the system.
It reads
[stem]
++++
\begin{array}{rl}
\mathbf{n} \cdot \mathbf{n} &= g\\
\mathbf{n} \cdot \left[ (-p\mathbf{I} + 2 \mu \mathbf{D}(\mathbf{u})) \ \mathbf{\tau}_i \right] &= f_i,\quad i=1,\ldots, d-1
\end{array}
++++
where stem:[d] is the geometrical dimension, stem:[\mathbf{n}] the unit ouward normal to the boundary and stem:[(\mathbf{\tau}_i)_{i=1,...,d-1}] the tangent vectors to the boundary

When we integrate by parts, only the tangential component of the normal stress is controled via the boundary condition.
The normal component of the normal stress remains to be controlled and this is done via the penalisation that imposes the normal component of the velocity.

Denote stem:[\Gamma_S] the part of the boundary with slip boundary conditions.

The variational formulation reads
[stem]
++++
\begin{align}
\int_\Omega \nabla \mathbf{u} : \nabla \mathbf{v} - \nabla\cdot \mathbf{v} p -  \nabla\cdot \mathbf{u} q + \int_{\Gamma_S} \mathbf{n} \cdot \left[ (-p\mathbf{I} + 2 \mu \mathbf{D}(\mathbf{u})) \ \mathbf{n} \right] \mathbf{v} \cdot \mathbf{n} &= \\
\sum_{i=1}^{d-1} \int_{\Gamma_S} f_i \mathbf{v} \cdot \mathbf{\tau}_i + \int_{\Gamma_S} \gamma (\mathbf{u} \cdot \mathbf{n}) (\mathbf{v} \cdot \mathbf{n})
\end{align}
++++



