---
category: workshop
tags:
  - feelpp
  - event
  - fud
header:
  image_fullwidth: header_unsplash_workshop.jpg
---
= 5-th Feel++ Users Days
:page-layout: page
:page-date: 2017-09-11
:page-author: prudhomm
:page-title:  5th Feel++ User Days
:page-subheadline:  "[fud-5]"
:page-teaser: "The 5th Feel++ User Days in Strasbourg from Sept 11 to Sept 14"
:page-liquid:
:page-toc: true
:toc:

The Center of Modeling and Simulation in Strasbourg as well as the Feel++ development team organize the "Fifth Feel++ User Days".
The FUD-5 will take place in Strasbourg at IRMA between September 11 and September 14 (included) 2017.

== Sponsors

The 5th Feel++ User days are sponsored by

 - link:http://www.cemosis.fr[Cemosis], the Center for Mathematical
   Modeling and Simulation in Strasbourg,

 - the EU EINFRA H2020 project link:http://mso4sc.eu[MSO4SC]

 - the Labex link:http://labex-irmia.u-strasbg.fr/[IRMIA]
 
 - the ANR Project http://www.vivabrain.fr[VIVABRAIN]

 - the ANR Project CHORUS

== Programme

We have special guests for these FUD 5.0.

 - Frédéric Bertrand (Unistra,IRMA)
 - Jacky Goetz (Inserm)
 - Gauther Follain (Unistra)
 - Charles Pivot (PPRIME)

=== Sept 11
    
[format="csv", options="header",grid=rows,cols="1,2,2"]
.Programme of Sept 11
|===
include::fud5-sept11.csv[]
|===

=== Sept 12

[format="csv", options="header",grid=rows,cols="1,2,2"]
.Programme of Sept 12
|===
include::fud5-sept12.csv[]
|===

=== Sept 13
    
[format="csv", options="header",grid=rows,cols="1,2,2"]
.Programme of Sept 13
|===
include::fud5-sept13.csv[]
|===

=== Sept 14

[format="csv", options="header",grid=rows,cols="1,2,2"]
.Programme of Sept 14
|===
include::fud5-sept14.csv[]
|===

=== Social event

There will be a Feel++ User Dinner on Sept 14 evening.


== Free (but Mandatory) Registration

Registration is free but mandatory for logistic reasons(breaks, lunches and social event on September 14).
The registration deadline is September, 8, 2017 at noon

++++
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdFz8dsrT-BHR2gRJV_pep7eVyGD7QlqOQi5498BklhWtLZjw/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
++++

== From the train station to the Institute

++++
<iframe src="https://www.google.com/maps/embed?pb=!1m29!1m12!1m3!1d10557.68585694684!2d7.740339418101108!3d48.58262847971634!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m14!1i0!3e3!4m5!1s0x4796c849fe2e6bbd%3A0xd960066e84c58c5!2sGare+Centrale%2C+Strasbourg!3m2!1d48.585266!2d7.7354519999999996!4m5!1s0x4796c8fe50b3eb29%3A0x66aa010dad7acb60!2sInstitut+de+Recherche+Math%C3%A9matique+Avanc%C3%A9e%2C+7+Rue+Ren%C3%A9+Descartes%2C+67000+Strasbourg!3m2!1d48.580455!2d7.762986!5e0!3m2!1sfr!2sfr!4v1425487485095" width="600" height="450" frameborder="0" style="border:0"></iframe>
++++

