---
category: publication
tags:
  - feelpp
  - publication
  - article
  - hemotum++
header:
  image_fullwidth: header_unsplash_publication.jpg
---
:hemotumpp: Hemotum++
= New preprint on the {hemotumpp} project
:page-layout: page
:page-date: 2017-10-03
:page-author: prudhomm
:page-title:  New preprint on the Hemotum++ project
:page-subheadline:  "[biorxiv2017]"
:page-teaser: "Hemodynamic forces tune the arrest, adhesion and extravasation of circulating tumor cells"
:page-liquid:
:feelpp: Feel++


Our work on _hemodynamic forces tuning the arrest, adhesion and extravasation of circulating tumor cells_ is available as preprint on biorxiv. 
https://www.biorxiv.org/content/early/2017/08/31/183046 +
This is a collaboration effort  with many people among which the leading team of link:http://www.goetzlab.com/[Jacky Goetz].
Regarding {feelpp}, the umbrella project is called link:http://www.cemosis.fr/projects/hemotumpp[{hemotumpp}].
Our work involved modelling the geometry and the blood flow in the tail of the zebrafish in 3D.
We used in particular our fluid-structure interaction toolbox to recover blood flow profiles at different location of the zebrafish vascular network and compare them with in-vivo measurements.


== Abstract

Metastatic seeding is driven by cell-intrinsic and environmental cues, yet the contribution of biomechanics is poorly known.
We aim to elucidate the impact of blood flow on the arrest and the extravasation of circulating tumor cells (CTCs) in vivo.
Using the zebrafish embryo, we show that arrest of CTCs occurs mostly in vessels with favorable flow profiles where flow forces control the adhesion efficacy of CTCs to the endothelium.
We biophysically identified the threshold values of flow and adhesion forces allowing successful arrest of CTCs.
In addition, flow forces fine-tune tumor cell extravasation by impairing the remodeling properties of the endothelium.
Importantly, we also observe endothelial remodeling at arrest sites of CTCs in mouse brain capillaries.
Finally, we observed that human supratentorial brain metastases preferably develop in areas with low perfusion.
Altogether, these results demonstrate that hemodynamic profiles at metastatic sites regulate key steps of extravasation preceding metastatic outgrowth. 

